version: '3.8'

services:
  web-app:
    container_name: golang
    build: .
    ports:
      - 8080:8080
    volumes:
      - .:/go-coffee-shop
    depends_on:
      - db
    restart: always
  
  db:
    image: postgres
    container_name: db
    ports:
      - 8000:5432
    environment:
      - POSTGRES_DB=aplikasiCoffeeShop
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=admin
